name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/*.yml'
      - 'project/build.properties'
      - 'package*.json'
  push:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/*.yml'
      - 'project/build.properties'
      - 'package*.json'

# For reporting test reports
permissions:
  checks: write

jobs:
  code_format:
    name: Code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: sbt
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
  test_js:
    name: Scala.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache ScalablyTyped artifacts
        id: cache-scalablytyped
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/local/org.scalablytyped
            ~/.sbt
            ~/.cache
          key: ${{ runner.os }}-scalablytyped
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: sbt
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - name: Install NPM modules
        run: npm install
      - name: Scala.js test
        run: JVM_OPTS=-Xmx4g ./sbt test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala.js


